# Generated by Django 5.0.6 on 2024-06-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmessage',
            name='show_on_guestbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestbookmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guestbookmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
