# Generated by Django 5.0.6 on 2024-06-25 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_guestbookmessage_show_on_guestbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookmessage',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='guestbookmessage',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
