# Generated by Django 5.0.6 on 2024-06-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_alter_guestbookmessage_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestbookMessage',
            new_name='Message',
        ),
    ]
